[build]
  publish = "dist"
  command = "yarn build"
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[functions."cron-background"]
  schedule = "*/15 * * * *"
  included_files=["functions/emails/*.liquid"]

[functions."cron"]
  included_files=["functions/emails/*.liquid"]

[functions."submission-created"]
  included_files=["functions/emails/*.liquid"]

[functions."approve"]
  included_files=["functions/emails/*.liquid"]

[functions."profile"]
  included_files=["functions/emails/*.liquid"]

[[plugins]]
  package = 'netlify-plugin-contextual-env'