[build]
  publish = "dist"
  command = "yarn build"
  functions = "functions/"

[functions."cron-background"]
  schedule = "*/15 * * * *"

[functions]
  include_files = "functions/emails/*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = 'netlify-plugin-contextual-env'

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Origin = "*"