[build]
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = 'netlify-plugin-contextual-env'

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Credentials = true
    Access-Control-Allow-Origin = 'https://localhost:8080'